### ISSUE TITLE
Checkov-Report.xml. Error : Root element is missing..

### ISSUE THREAD

**Issue by TheIronRock95** [AErmie/Terraform-Real-World-Edition#8]
I'm using the "checkov-terraform-quality-check-pipeline.yml" for testing my code I only run into the problem that the .xml file is not getting published.

i have an exact copy of your pipline and when using the step two  `sed -i' $d ` I get the error:

> Failed to read /home/vsts/work/1/s/CheckovReport/Checkov-Report.xml. Error: Root element is missing .. 

if I don't use the `sed -i'  d` I get the following error: 

> No Result Found to Publish '/home/vsts/work/1/s/CheckovReport/Checkov-Report.xml'.

your help is appreciated

**Comment by AErmie** [comment]
Hi @TheIronRock95, the bit of code with `sed -i '$d'` is no longer needed. The BridgeCrew team discovered that if you are trying to run Checkov from a Docker container, if you omit the -t property the output is correct. 

This is the Docker run command ...

`docker run -v $(System.DefaultWorkingDirectory)/Some-Path-To-Your-Terraform-Code:/tf bridgecrew/checkov --directory /tf --output junitxml > $(System.DefaultWorkingDirectory)/Checkov-Report.xml`

And to publish the test results, this is the code... 

```
- task: PublishTestResults@2
        displayName: Publish Checkov Test Results
        condition: succeededOrFailed()
        inputs:
          testResultsFormat: 'JUnit' # Options JUnit, NUnit, VSTest, xUnit, cTest
          testResultsFiles: '**/*Checkov-Report.xml'
          searchFolder: '$(System.DefaultWorkingDirectory)'
          mergeTestResults: false
          testRunTitle: Checkov Scan
          failTaskOnFailedTests: false
          publishRunAttachments: true
```

**Comment by TheIronRock95** [comment]
Hi @AErmie , i changed the code but i still receive the error message:
> No Result Found to Publish '/home/vsts/work/1/s/CheckovReport/Checkov-Report.xml'. 

My Azure DevOps pipeline looks like this:

```
stages:
- stage: QualityCheckStage
  displayName: Quality Check Stage
  jobs:
    - job: QualityTestJob
      displayName: Run Checkov
      steps:
      - script: |
          mkdir CheckovReport
          docker pull bridgecrew/checkov
          docker run -v $(System.DefaultWorkingDirectory)/Module:/tf bridgecrew/checkov --directory /tf --output junitxml > $(System.DefaultWorkingDirectory)/CheckovReport/Checkov-Report.xml
        displayName: 'Checkov Static Code Analysis'
        name: CheckovScan
        condition: always()

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact: Checkov Report'
        condition: succeededOrFailed()
        inputs:
          PathtoPublish: '$(System.DefaultWorkingDirectory)/CheckovReport'
          ArtifactName: CheckovReport

      - task: PublishTestResults@2
        displayName: Publish Checkov Test Results
        condition: succeededOrFailed()
        inputs:
          testResultsFormat: 'JUnit'
          testResultsFiles: '**/*Checkov-Report.xml'
          searchFolder: '$(System.DefaultWorkingDirectory)'
          mergeTestResults: false
          testRunTitle: Checkov Scan
          failTaskOnFailedTests: false
          publishRunAttachments: true
```

```
